pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  batch: true
  branches:
    include:
    - refs/heads/*
    exclude:
    - example/
    - README.md

variables:
  imageName: 'azuredevops-terraform-agent'
  terraformVersion: 0.11.13
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI

steps:
- bash: docker build -f $(system.defaultWorkingDirectory)/Dockerfile -t $(registryName)/$(imageName):$(terraformVersion) -t $(registryName)/$(imageName):latest --build-arg TERRAFORM_VERSION=$(terraformVersion) $(system.defaultWorkingDirectory)
  displayName: 'docker build'

- bash: docker login -u $(registryLogin) -p $(registryPassword)
  displayName: 'docker login'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

- bash: |
    docker push $(registryName)/$(imageName):$(terraformVersion)
    docker push $(registryName)/$(imageName):latest
  displayName: 'docker push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
